db.Currency.insert({"_id": 1, "currencyAlternateKey": "AED", "currencyName": "Emirati Dirham"})
db.Currency.insert({"_id": 2, "currencyAlternateKey": "AFA", "currencyName": "Afghani"})
db.Currency.insert({"_id": 3, "currencyAlternateKey": "ALL", "currencyName": "Lek"})
db.Currency.insert({"_id": 4, "currencyAlternateKey": "AMD", "currencyName": "Armenian Dram"})
db.Currency.insert({"_id": 5, "currencyAlternateKey": "ANG", "currencyName": "Netherlands Antillian Guilder"})
db.Currency.insert({"_id": 6, "currencyAlternateKey": "AOA", "currencyName": "Kwanza"})
db.Currency.insert({"_id": 7, "currencyAlternateKey": "ARS", "currencyName": "Argentine Peso"})
db.Currency.insert({"_id": 8, "currencyAlternateKey": "ATS", "currencyName": "Shilling"})
db.Currency.insert({"_id": 9, "currencyAlternateKey": "AUD", "currencyName": "Australian Dollar"})
db.Currency.insert({"_id": 10, "currencyAlternateKey": "AWG", "currencyName": "Aruban Guilder"})
db.Currency.insert({"_id": 11, "currencyAlternateKey": "AZM", "currencyName": "Azerbaijanian Manat"})
db.Currency.insert({"_id": 12, "currencyAlternateKey": "BBD", "currencyName": "Barbados Dollar"})
db.Currency.insert({"_id": 13, "currencyAlternateKey": "BDT", "currencyName": "Taka"})
db.Currency.insert({"_id": 14, "currencyAlternateKey": "BEF", "currencyName": "Belgian Franc"})
db.Currency.insert({"_id": 15, "currencyAlternateKey": "BGN", "currencyName": "Bulgarian Lev"})
db.Currency.insert({"_id": 16, "currencyAlternateKey": "BHD", "currencyName": "Bahraini Dinar"})
db.Currency.insert({"_id": 17, "currencyAlternateKey": "BND", "currencyName": "Brunei Dollar"})
db.Currency.insert({"_id": 18, "currencyAlternateKey": "BOB", "currencyName": "Boliviano"})
db.Currency.insert({"_id": 19, "currencyAlternateKey": "BRL", "currencyName": "Brazilian Real"})
db.Currency.insert({"_id": 20, "currencyAlternateKey": "BSD", "currencyName": "Bahamian Dollar"})
db.Currency.insert({"_id": 21, "currencyAlternateKey": "BTN", "currencyName": "Ngultrum"})
db.Currency.insert({"_id": 22, "currencyAlternateKey": "CAD", "currencyName": "Canadian Dollar"})
db.Currency.insert({"_id": 23, "currencyAlternateKey": "CHF", "currencyName": "Swiss Franc"})
db.Currency.insert({"_id": 24, "currencyAlternateKey": "CLP", "currencyName": "Chilean Peso"})
db.Currency.insert({"_id": 25, "currencyAlternateKey": "CNY", "currencyName": "Yuan Renminbi"})
db.Currency.insert({"_id": 26, "currencyAlternateKey": "COP", "currencyName": "Colombian Peso"})
db.Currency.insert({"_id": 27, "currencyAlternateKey": "CRC", "currencyName": "Costa Rican Colon"})
db.Currency.insert({"_id": 28, "currencyAlternateKey": "CYP", "currencyName": "Cyprus Pound"})
db.Currency.insert({"_id": 29, "currencyAlternateKey": "CZK", "currencyName": "Czech Koruna"})
db.Currency.insert({"_id": 30, "currencyAlternateKey": "DEM", "currencyName": "Deutsche Mark"})
db.Currency.insert({"_id": 31, "currencyAlternateKey": "DKK", "currencyName": "Danish Krone"})
db.Currency.insert({"_id": 32, "currencyAlternateKey": "DOP", "currencyName": "Dominican Peso"})
db.Currency.insert({"_id": 33, "currencyAlternateKey": "DZD", "currencyName": "Algerian Dinar"})
db.Currency.insert({"_id": 34, "currencyAlternateKey": "EEK", "currencyName": "Kroon"})
db.Currency.insert({"_id": 35, "currencyAlternateKey": "EGP", "currencyName": "Egyptian Pound"})
db.Currency.insert({"_id": 36, "currencyAlternateKey": "ESP", "currencyName": "Spanish Peseta"})
db.Currency.insert({"_id": 37, "currencyAlternateKey": "EUR", "currencyName": "EURO"})
db.Currency.insert({"_id": 38, "currencyAlternateKey": "FIM", "currencyName": "Markka"})
db.Currency.insert({"_id": 39, "currencyAlternateKey": "FJD", "currencyName": "Fiji Dollar"})
db.Currency.insert({"_id": 40, "currencyAlternateKey": "FRF", "currencyName": "French Franc"})
db.Currency.insert({"_id": 41, "currencyAlternateKey": "GBP", "currencyName": "United Kingdom Pound"})
db.Currency.insert({"_id": 42, "currencyAlternateKey": "GHC", "currencyName": "Cedi"})
db.Currency.insert({"_id": 43, "currencyAlternateKey": "GRD", "currencyName": "Drachma"})
db.Currency.insert({"_id": 44, "currencyAlternateKey": "GTQ", "currencyName": "Quetzal"})
db.Currency.insert({"_id": 45, "currencyAlternateKey": "HKD", "currencyName": "Hong Kong Dollar"})
db.Currency.insert({"_id": 46, "currencyAlternateKey": "HRK", "currencyName": "Croatian Kuna"})
db.Currency.insert({"_id": 47, "currencyAlternateKey": "HUF", "currencyName": "Forint"})
db.Currency.insert({"_id": 48, "currencyAlternateKey": "IDR", "currencyName": "Rupiah"})
db.Currency.insert({"_id": 49, "currencyAlternateKey": "IEP", "currencyName": "Irish Pound"})
db.Currency.insert({"_id": 50, "currencyAlternateKey": "ILS", "currencyName": "New Israeli Shekel"})
db.Currency.insert({"_id": 51, "currencyAlternateKey": "INR", "currencyName": "Indian Rupee"})
db.Currency.insert({"_id": 52, "currencyAlternateKey": "ISK", "currencyName": "Iceland Krona"})
db.Currency.insert({"_id": 53, "currencyAlternateKey": "ITL", "currencyName": "Italian Lira"})
db.Currency.insert({"_id": 54, "currencyAlternateKey": "JMD", "currencyName": "Jamaican Dollar"})
db.Currency.insert({"_id": 55, "currencyAlternateKey": "JOD", "currencyName": "Jordanian Dinar"})
db.Currency.insert({"_id": 56, "currencyAlternateKey": "JPY", "currencyName": "Yen"})
db.Currency.insert({"_id": 57, "currencyAlternateKey": "KES", "currencyName": "Kenyan Shilling"})
db.Currency.insert({"_id": 58, "currencyAlternateKey": "KRW", "currencyName": "Won"})
db.Currency.insert({"_id": 59, "currencyAlternateKey": "KWD", "currencyName": "Kuwaiti Dinar"})
db.Currency.insert({"_id": 60, "currencyAlternateKey": "LBP", "currencyName": "Lebanese Pound"})
db.Currency.insert({"_id": 61, "currencyAlternateKey": "LKR", "currencyName": "Sri Lankan Rupee"})
db.Currency.insert({"_id": 62, "currencyAlternateKey": "LTL", "currencyName": "Lithuanian Litas"})
db.Currency.insert({"_id": 63, "currencyAlternateKey": "LVL", "currencyName": "Latvian Lats"})
db.Currency.insert({"_id": 64, "currencyAlternateKey": "MAD", "currencyName": "Moroccan Dirham"})
db.Currency.insert({"_id": 65, "currencyAlternateKey": "MTL", "currencyName": "Maltese Lira"})
db.Currency.insert({"_id": 66, "currencyAlternateKey": "MUR", "currencyName": "Mauritius Rupee"})
db.Currency.insert({"_id": 67, "currencyAlternateKey": "MVR", "currencyName": "Rufiyaa"})
db.Currency.insert({"_id": 68, "currencyAlternateKey": "MXN", "currencyName": "Mexican Peso"})
db.Currency.insert({"_id": 69, "currencyAlternateKey": "MYR", "currencyName": "Malaysian Ringgit"})
db.Currency.insert({"_id": 70, "currencyAlternateKey": "NAD", "currencyName": "Namibia Dollar"})
db.Currency.insert({"_id": 71, "currencyAlternateKey": "NGN", "currencyName": "Naira"})
db.Currency.insert({"_id": 72, "currencyAlternateKey": "NLG", "currencyName": "Netherlands Guilder"})
db.Currency.insert({"_id": 73, "currencyAlternateKey": "NOK", "currencyName": "Norwegian Krone"})
db.Currency.insert({"_id": 74, "currencyAlternateKey": "NPR", "currencyName": "Nepalese Rupee"})
db.Currency.insert({"_id": 75, "currencyAlternateKey": "NZD", "currencyName": "New Zealand Dollar"})
db.Currency.insert({"_id": 76, "currencyAlternateKey": "OMR", "currencyName": "Omani Rial"})
db.Currency.insert({"_id": 77, "currencyAlternateKey": "PAB", "currencyName": "Balboa"})
db.Currency.insert({"_id": 78, "currencyAlternateKey": "PEN", "currencyName": "Nuevo Sol"})
db.Currency.insert({"_id": 79, "currencyAlternateKey": "PHP", "currencyName": "Philippine Peso"})
db.Currency.insert({"_id": 80, "currencyAlternateKey": "PKR", "currencyName": "Pakistan Rupee"})
db.Currency.insert({"_id": 81, "currencyAlternateKey": "PLN", "currencyName": "Zloty"})
db.Currency.insert({"_id": 82, "currencyAlternateKey": "PLZ", "currencyName": "Polish Zloty(old)"})
db.Currency.insert({"_id": 83, "currencyAlternateKey": "PTE", "currencyName": "Portuguese Escudo"})
db.Currency.insert({"_id": 84, "currencyAlternateKey": "PYG", "currencyName": "Guarani"})
db.Currency.insert({"_id": 85, "currencyAlternateKey": "ROL", "currencyName": "Leu"})
db.Currency.insert({"_id": 86, "currencyAlternateKey": "RUB", "currencyName": "Russian Ruble"})
db.Currency.insert({"_id": 87, "currencyAlternateKey": "RUR", "currencyName": "Russian Ruble(old)"})
db.Currency.insert({"_id": 88, "currencyAlternateKey": "SAR", "currencyName": "Saudi Riyal"})
db.Currency.insert({"_id": 89, "currencyAlternateKey": "SEK", "currencyName": "Swedish Krona"})
db.Currency.insert({"_id": 90, "currencyAlternateKey": "SGD", "currencyName": "Singapore Dollar"})
db.Currency.insert({"_id": 91, "currencyAlternateKey": "SIT", "currencyName": "Tolar"})
db.Currency.insert({"_id": 92, "currencyAlternateKey": "SKK", "currencyName": "Slovak Koruna"})
db.Currency.insert({"_id": 93, "currencyAlternateKey": "SVC", "currencyName": "El Salvador Colon"})
db.Currency.insert({"_id": 94, "currencyAlternateKey": "THB", "currencyName": "Baht"})
db.Currency.insert({"_id": 95, "currencyAlternateKey": "TND", "currencyName": "Tunisian Dinar"})
db.Currency.insert({"_id": 96, "currencyAlternateKey": "TRL", "currencyName": "Turkish Lira"})
db.Currency.insert({"_id": 97, "currencyAlternateKey": "TTD", "currencyName": "Trinidad and Tobago Dollar"})
db.Currency.insert({"_id": 98, "currencyAlternateKey": "TWD", "currencyName": "New Taiwan Dollar"})
db.Currency.insert({"_id": 99, "currencyAlternateKey": "USD", "currencyName": "US Dollar"})
db.Currency.insert({"_id": 100, "currencyAlternateKey": "UYU", "currencyName": "Uruguayan Peso"})
db.Currency.insert({"_id": 101, "currencyAlternateKey": "VEB", "currencyName": "Bolivar"})
db.Currency.insert({"_id": 102, "currencyAlternateKey": "VND", "currencyName": "Dong"})
db.Currency.insert({"_id": 103, "currencyAlternateKey": "XOF", "currencyName": "CFA Franc BCEAO"})
db.Currency.insert({"_id": 104, "currencyAlternateKey": "ZAR", "currencyName": "Rand"})
db.Currency.insert({"_id": 105, "currencyAlternateKey": "ZWD", "currencyName": "Zimbabwe Dollar"})
