db.SalesTerritory.insert({"_id": 1, "salesTerritoryCountry": "Australia", "salesTerritoryRegion": "Australia", "salesTerritoryGroup": "Pacific"})
db.SalesTerritory.insert({"_id": 2, "salesTerritoryCountry": "Canada", "salesTerritoryRegion": "Canada", "salesTerritoryGroup": "North America"})
db.SalesTerritory.insert({"_id": 3, "salesTerritoryCountry": "France", "salesTerritoryRegion": "France", "salesTerritoryGroup": "Europe"})
db.SalesTerritory.insert({"_id": 4, "salesTerritoryCountry": "Germany", "salesTerritoryRegion": "Germany", "salesTerritoryGroup": "Europe"})
db.SalesTerritory.insert({"_id": 5, "salesTerritoryCountry": "NA", "salesTerritoryRegion": "NA", "salesTerritoryGroup": "NA"})
db.SalesTerritory.insert({"_id": 6, "salesTerritoryCountry": "United Kingdom", "salesTerritoryRegion": "United Kingdom", "salesTerritoryGroup": "Europe"})
db.SalesTerritory.insert({"_id": 7, "salesTerritoryCountry": "United States", "salesTerritoryRegion": "Central", "salesTerritoryGroup": "North America"})
db.SalesTerritory.insert({"_id": 8, "salesTerritoryCountry": "United States", "salesTerritoryRegion": "Northeast", "salesTerritoryGroup": "North America"})
db.SalesTerritory.insert({"_id": 9, "salesTerritoryCountry": "United States", "salesTerritoryRegion": "Northwest", "salesTerritoryGroup": "North America"})
db.SalesTerritory.insert({"_id": 10, "salesTerritoryCountry": "United States", "salesTerritoryRegion": "Southeast", "salesTerritoryGroup": "North America"})
db.SalesTerritory.insert({"_id": 11, "salesTerritoryCountry": "United States", "salesTerritoryRegion": "Southwest", "salesTerritoryGroup": "North America"})
