db.SubCategory.insert({"_id": 1, "frenchSubCategoryName": "Antivol", "englishSubCategoryName": "Locks", "spanishSubCategoryName": "Candado", "categoryKey": 1})
db.SubCategory.insert({"_id": 2, "frenchSubCategoryName": "Axe de pédalier", "englishSubCategoryName": "Bottom Brackets", "spanishSubCategoryName": "Eje de pedalier", "categoryKey": 2})
db.SubCategory.insert({"_id": 3, "frenchSubCategoryName": "Barre d'appui", "englishSubCategoryName": "Handlebars", "spanishSubCategoryName": "Barra", "categoryKey": 2})
db.SubCategory.insert({"_id": 4, "frenchSubCategoryName": "Bidon et porte-bidon", "englishSubCategoryName": "Bottles and Cages", "spanishSubCategoryName": "Portabotellas y botella", "categoryKey": 1})
db.SubCategory.insert({"_id": 5, "frenchSubCategoryName": "Cadre de vélo de randonnée", "englishSubCategoryName": "Touring Frames", "spanishSubCategoryName": "Cuadro de paseo", "categoryKey": 2})
db.SubCategory.insert({"_id": 6, "frenchSubCategoryName": "Cadre de vélo de route", "englishSubCategoryName": "Road Frames", "spanishSubCategoryName": "Cuadro de carretera", "categoryKey": 2})
db.SubCategory.insert({"_id": 7, "frenchSubCategoryName": "Cadre de VTT", "englishSubCategoryName": "Mountain Frames", "spanishSubCategoryName": "Cuadro de montaña", "categoryKey": 2})
db.SubCategory.insert({"_id": 8, "frenchSubCategoryName": "Casque", "englishSubCategoryName": "Helmets", "spanishSubCategoryName": "Casco", "categoryKey": 1})
db.SubCategory.insert({"_id": 9, "frenchSubCategoryName": "Casquette", "englishSubCategoryName": "Caps", "spanishSubCategoryName": "Gorra", "categoryKey": 4})
db.SubCategory.insert({"_id": 10, "frenchSubCategoryName": "Chaîne", "englishSubCategoryName": "Chains", "spanishSubCategoryName": "Cadena", "categoryKey": 2})
db.SubCategory.insert({"_id": 11, "frenchSubCategoryName": "Chaussettes", "englishSubCategoryName": "Socks", "spanishSubCategoryName": "Calcetines", "categoryKey": 4})
db.SubCategory.insert({"_id": 12, "frenchSubCategoryName": "Collants", "englishSubCategoryName": "Tights", "spanishSubCategoryName": "Mallas", "categoryKey": 4})
db.SubCategory.insert({"_id": 13, "frenchSubCategoryName": "Cuissards", "englishSubCategoryName": "Shorts", "spanishSubCategoryName": "Pantalones cortos", "categoryKey": 4})
db.SubCategory.insert({"_id": 14, "frenchSubCategoryName": "Cuissards avec bretelles", "englishSubCategoryName": "Bib-Shorts", "spanishSubCategoryName": "Culote corto", "categoryKey": 4})
db.SubCategory.insert({"_id": 15, "frenchSubCategoryName": "Dérailleur", "englishSubCategoryName": "Derailleurs", "spanishSubCategoryName": "Desviador", "categoryKey": 2})
db.SubCategory.insert({"_id": 16, "frenchSubCategoryName": "Éclairage", "englishSubCategoryName": "Lights", "spanishSubCategoryName": "Luz", "categoryKey": 1})
db.SubCategory.insert({"_id": 17, "frenchSubCategoryName": "Fourche", "englishSubCategoryName": "Forks", "spanishSubCategoryName": "Horquilla", "categoryKey": 2})
db.SubCategory.insert({"_id": 18, "frenchSubCategoryName": "Freins", "englishSubCategoryName": "Brakes", "spanishSubCategoryName": "Frenos", "categoryKey": 2})
db.SubCategory.insert({"_id": 19, "frenchSubCategoryName": "Gants", "englishSubCategoryName": "Gloves", "spanishSubCategoryName": "Guantes", "categoryKey": 4})
db.SubCategory.insert({"_id": 20, "frenchSubCategoryName": "Garde-boue", "englishSubCategoryName": "Fenders", "spanishSubCategoryName": "Guardabarros", "categoryKey": 1})
db.SubCategory.insert({"_id": 21, "frenchSubCategoryName": "Jeu de direction", "englishSubCategoryName": "Headsets", "spanishSubCategoryName": "Dirección", "categoryKey": 2})
db.SubCategory.insert({"_id": 22, "frenchSubCategoryName": "Maillot", "englishSubCategoryName": "Jerseys", "spanishSubCategoryName": "Jersey", "categoryKey": 4})
db.SubCategory.insert({"_id": 23, "frenchSubCategoryName": "Nettoyant", "englishSubCategoryName": "Cleaners", "spanishSubCategoryName": "Limpiador", "categoryKey": 1})
db.SubCategory.insert({"_id": 24, "frenchSubCategoryName": "Pédale", "englishSubCategoryName": "Pedals", "spanishSubCategoryName": "Pedal", "categoryKey": 2})
db.SubCategory.insert({"_id": 25, "frenchSubCategoryName": "Pédalier", "englishSubCategoryName": "Cranksets", "spanishSubCategoryName": "Bielas", "categoryKey": 2})
db.SubCategory.insert({"_id": 26, "frenchSubCategoryName": "Pneu et chambre à air", "englishSubCategoryName": "Tires and Tubes", "spanishSubCategoryName": "Cubierta y cámara", "categoryKey": 1})
db.SubCategory.insert({"_id": 27, "frenchSubCategoryName": "Pompe", "englishSubCategoryName": "Pumps", "spanishSubCategoryName": "Bomba", "categoryKey": 1})
db.SubCategory.insert({"_id": 28, "frenchSubCategoryName": "Porte-vélo", "englishSubCategoryName": "Bike Racks", "spanishSubCategoryName": "Portabicicletas", "categoryKey": 1})
db.SubCategory.insert({"_id": 29, "frenchSubCategoryName": "Range-vélo", "englishSubCategoryName": "Bike Stands", "spanishSubCategoryName": "Soporte para bicicletas", "categoryKey": 1})
db.SubCategory.insert({"_id": 30, "frenchSubCategoryName": "Roue", "englishSubCategoryName": "Wheels", "spanishSubCategoryName": "Rueda", "categoryKey": 2})
db.SubCategory.insert({"_id": 31, "frenchSubCategoryName": "Sac d'hydratation", "englishSubCategoryName": "Hydration Packs", "spanishSubCategoryName": "Sistema de hidratación", "categoryKey": 1})
db.SubCategory.insert({"_id": 32, "frenchSubCategoryName": "Sacoche", "englishSubCategoryName": "Panniers", "spanishSubCategoryName": "Cesta", "categoryKey": 1})
db.SubCategory.insert({"_id": 33, "frenchSubCategoryName": "Selle", "englishSubCategoryName": "Saddles", "spanishSubCategoryName": "Sillín", "categoryKey": 2})
db.SubCategory.insert({"_id": 34, "frenchSubCategoryName": "Vélo de randonnée", "englishSubCategoryName": "Touring Bikes", "spanishSubCategoryName": "Bicicleta de paseo", "categoryKey": 3})
db.SubCategory.insert({"_id": 35, "frenchSubCategoryName": "Vélo de route", "englishSubCategoryName": "Road Bikes", "spanishSubCategoryName": "Bicicleta de carretera", "categoryKey": 3})
db.SubCategory.insert({"_id": 36, "frenchSubCategoryName": "Veste", "englishSubCategoryName": "Vests", "spanishSubCategoryName": "Camiseta", "categoryKey": 4})
db.SubCategory.insert({"_id": 37, "frenchSubCategoryName": "VTT", "englishSubCategoryName": "Mountain Bikes", "spanishSubCategoryName": "Bicicleta de montaña", "categoryKey": 3})
